services:
  _defaults:
    public: true

  # GRID
  openarticles.grid.definition.factory:
    public: true
    class : 'Vex6\OpenArticles\Grid\Definition\Factory\ArticleDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
  
  openarticles.grid.query_builder:
    class: 'Vex6\OpenArticles\Grid\Query\ArticleQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'

  openarticles.grid.data.factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@openarticles.grid.query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'Articles'

  openarticles.grid.data.factory.decorator:
    class: 'Vex6\OpenArticles\Grid\Data\Factory\ArticleGridDataFactory'
    arguments:
      - '@openarticles.grid.data.factory'
      - '@openarticles.adapter.article_logo_thumbnail_provider'

  openarticles.grid.grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@openarticles.grid.definition.factory'
      - '@openarticles.grid.data.factory.decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

 # IMAGE PROVIDER

  openarticles.adapter.article_logo_thumbnail_provider:
    class: 'Vex6\OpenArticles\Adapter\LogoThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'

 # FORM

  openarticles.type.article:
    class: 'Vex6\OpenArticles\Form\Type\ArticleType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@openarticles.repository.article_repository'
    tags:
      - { name: form.type }

  openarticles.form.identifiable.object.builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Vex6\OpenArticles\Form\Type\ArticleType'
      - '@openarticles.form.identifiable_object.data.provider'

  openarticles.form.identifiable_object.data.provider:
    class: 'Vex6\OpenArticles\Form\Provider\ArticleFormDataProvider'
    arguments:
      - '@openarticles.repository.article_repository'


  # COMMAND HANDLER

  openarticles.command.builder.article:
    class: 'Vex6\OpenArticles\CommandBuilder\ArticleCommandBuilder'

  openarticles.form.identifiable.object.data.handler:
    class: 'Vex6\OpenArticles\Form\DataHandler\ArticleFormDataHandler'
    arguments:
      - '@prestashop.core.command_bus'
      - '@openarticles.command.builder.article'

  openarticles.form.identifiable.object.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@openarticles.form.identifiable.object.data.handler'

  openarticles.command.handler.add_article:
    class: 'Vex6\OpenArticles\CommandHandler\AddArticleCommandHandler'
    arguments:
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Vex6\OpenArticles\Command\AddArticleCommand' }

  openarticles.command.handler.edit_article:
    class: 'Vex6\OpenArticles\CommandHandler\EditArticleCommandHandler'
    arguments:
      - '@prestashop.core.admin.lang.repository'
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Vex6\OpenArticles\Command\EditArticleCommand' }

  openarticles.command.handler.delete_article:
    class: 'Vex6\OpenArticles\CommandHandler\DeleteArticleCommandHandler'
    arguments:
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Vex6\OpenArticles\Command\DeleteArticleCommand' }

  openarticles.command_handler.bulk_delete_article_handler:
    class: Vex6\OpenArticles\CommandHandler\BulkDeleteArticleCommandHandler
    arguments:
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: Vex6\OpenArticles\Command\BulkDeleteArticleCommand

  openarticles.command.handler.toggle_article:
    class: 'Vex6\OpenArticles\CommandHandler\ToggleArticleCommandHandler'
    arguments:
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Vex6\OpenArticles\Command\ToggleArticleCommand' }

  openarticles.command_handler.bulk_enable_article_handler:
    class: Vex6\OpenArticles\CommandHandler\BulkEnableArticleCommandHandler
    arguments:
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: Vex6\OpenArticles\Command\BulkEnableArticleCommand

  openarticles.command_handler.bulk_disable_article_handler:
    class: Vex6\OpenArticles\CommandHandler\BulkDisableArticleCommandHandler
    arguments:
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: Vex6\OpenArticles\Command\BulkDisableArticleCommand

  openarticles.command_handler.update_article_position_handler:
    class: Vex6\OpenArticles\CommandHandler\UpdateArticlePositionCommandHandler
    arguments:
      - '@openarticles.repository.article_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: Vex6\OpenArticles\Command\UpdateArticlePositionCommand

  # Query handler

  openarticles.query.handler.toggle.article:
    class: Vex6\OpenArticles\QueryHandler\GetArticleStateHandler
    arguments:
      - '@openarticles.repository.article_repository'
    tags:
      - name: tactician.handler
        command: Vex6\OpenArticles\Query\GetArticleState

  # REPOSITORY

  openarticles.repository.article_repository:
    class: Vex6\OpenArticles\Repository\ArticleRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - Vex6\OpenArticles\Entity\OpenArticles