oit_article_index:
  path: /
  methods: GET
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::indexAction'
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'


oit_article_search:
  path: /
  methods: POST
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::searchAction'
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'

oit_article_create:
  path: /create
  methods: [GET, POST]
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::createAction'
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'

oit_article_edit:
  path: /{articleId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::editAction'
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'
  requirements:
    articleId: \d+

oit_article_delete:
  path: /{articleId}/delete
  methods: POST
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::deleteAction'
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'
  requirements:
    articleId: \d+

oit_delete_image:
  path: /{articleId}/delete/image
  methods: [POST]
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::deleteImageAction'
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'
  requirements:
    articleId: \d+

oit_delete_bulk:
  path: /delete-bulk
  methods: POST
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::deleteBulkAction'
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

oit_toggle_status:
  path: /{articleId}/toggle-status
  methods: [GET, POST]
  defaults:
    _controller: Vex6\OpenArticles\Controller\AdminOpenArticles::toggleAction
    _disable_module_prefix: true
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'
  requirements:
    articleId: \d+

oit_bulk_status_disable:
  path: /bulk-disable-status
  methods: [POST]
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::bulkStatusDisableAction'
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

oit_bulk_status_enable:
  path: /bulk-enable-status
  methods: [POST]
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::bulkStatusEnableAction'
    _legacy_controller: 'AdminOpenArticles'
    _legacy_link: 'AdminOpenArticles'

oit_update_positions:
  path: /update-positions
  methods: [POST]
  defaults:
    _controller: 'Vex6\OpenArticles\Controller\AdminOpenArticles::updatePositionsAction'
    _legacy_controller: AdminOpenArticles
    _legacy_link: 'AdminOpenArticles'

oit_article_export:
  path: /export
  methods: [GET]
  defaults:
    _controller: Vex6\OpenArticles\Controller\AdminOpenArticles::exportAction
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles