services:
  _defaults:
    public: true

  # REPOSITORY

  openarticles.repository.article_repository:
    class: Vex6\OpenArticles\Repository\ArticleRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - Vex6\OpenArticles\Entity\OpenArticles