<?php


use Vex6\OpenArticles\Repository\ArticleRepository;

class openarticlesArticleModuleFrontController extends ModuleFrontController {

    /**
     * @var array
     */
    private $article;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        /**
         * @var ArticleRepository $repository
         */
        $repository = $this->module->get('openarticles.repository.article_repository');
        $this->article = $repository->getFrontArticle((int)Tools::getValue('articleId') , $this->context->language->id);

    }

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub
        $this->context->smarty->assign(array(
            'article' => $this->article
        ));
        $this->setTemplate('module:openarticles/views/templates/front/article.tpl');
    }

    public function getBreadcrumbLinks()
    {
        $breadcrumb = parent::getBreadcrumbLinks();

        $breadcrumb['links'][] = [
            'title' => $this->trans('Mes super articles', [], 'Modules.Openarticles.Front'),
            'url' => $this->context->link->getModuleLink(
                $this->module->name, 'articles'
            )
        ];

        $breadcrumb['links'][] = [
            'title' => $this->trans($this->article['title'], [], 'Modules.Openarticles.Front'),
            'url' => "#"
        ];

        return $breadcrumb;
    }
}