<?php


use Vex6\OpenArticles\Repository\ArticleRepository;

class openarticlesArticlesModuleFrontController extends ModuleFrontController {

    /**
     * @var array
     */
    private $articles;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        /**
         * @var ArticleRepository $repository
         */
        $repository = $this->module->get('openarticles.repository.article_repository');
        $this->articles = $repository->getFrontData($this->context->language->id, 20);

    }

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub
        $this->context->smarty->assign(array(
            'articles' => $this->articles
        ));
        $this->setTemplate('module:openarticles/views/templates/front/articles.tpl');
    }

    public function getBreadcrumbLinks()
    {
        $breadcrumb = parent::getBreadcrumbLinks();

        $breadcrumb['links'][] = [
            'title' => $this->trans('Mes super articles', [], 'Modules.Openarticles.Front'),
            'url' => $this->context->link->getModuleLink(
                $this->module->name, 'articles'
            )
        ];



        return $breadcrumb;
    }
}